/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_pnehrer_logging_SystemLogHandler */

#ifndef _Included_com_pnehrer_logging_SystemLogHandler
#define _Included_com_pnehrer_logging_SystemLogHandler
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: offValue */
/* Inaccessible static: levelMap */
/*
 * Class:     com_pnehrer_logging_SystemLogHandler
 * Method:    openLog
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_pnehrer_logging_SystemLogHandler_openLog
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_pnehrer_logging_SystemLogHandler
 * Method:    closeLog
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_pnehrer_logging_SystemLogHandler_closeLog
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_pnehrer_logging_SystemLogHandler
 * Method:    writeLog
 * Signature: (IILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_pnehrer_logging_SystemLogHandler_writeLog
  (JNIEnv *, jclass, jint, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
